server:
  port: 8081
xxl:
  job:
    admin-addresses: http://localhost:8080/xxl-job-admin
    accessToken: 163766
    appname: zyx-executor
    ddress:
    ip:
    port: 9999
    logpath: ~/xxl-job/logs
    logretentiondays: 30
